### ISSUE TITLE
Test dataLoader's bbox is empty

### ISSUE THREAD

**Issue by zhi-dian** [sejong-rcv/INSANet#2]
Hi, thank you for your fantastic work! I'm a bit confused on your dataset class. When condition is not "train", the boxes is just a [0,0,0,0,-1] array without extension from the annotation file. Does it mean that the model doesn't need annotations during evaluation?
![image](https://github.com/sejong-rcv/INSANet/assets/104620617/ab15d992-843a-4cd9-9e37-2e2bd49e20dd)

**Comment by childult-programmer** [comment]
Hi @zhi-dian,

Thank you for your interest and kind words. As you mentioned, there is no need to bounding boxes for assignment when the condition is not "train" ("evaluation" step). It's just there for convenience when formatting.

Thanks,
Sangin

**Comment by childult-programmer** [comment]
Reopen if issue persists. Thanks!

> Hi, thank you for your fantastic work! I'm a bit confused on your dataset class. When condition is not "train", the boxes is just a [0,0,0,0,-1] array without extension from the annotation file. Does it mean that the model doesn't need annotations during evaluation? ![image](https://private-user-images.githubusercontent.com/104620617/326095322-ab15d992-843a-4cd9-9e37-2e2bd49e20dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjY4MDYsIm5iZiI6MTcxNDQ2NjUwNiwicGF0aCI6Ii8xMDQ2MjA2MTcvMzI2MDk1MzIyLWFiMTVkOTkyLTg0M2EtNGNkOS05ZTM3LTJlMmJkNDllMjBkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwODQxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODI3M2Y3NDNmMzM0MzZhNTJhOTUwMWNiODk3ZTUzZjc4NmYwN2MzYmQ2YzcyZGZkZDVhZGE3NzM4YWM4ZGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fwz8L7Vyp4NQ9sIR1ekumk8wRa9AC_yiC_7Xpzm-bVc)

**Comment by childult-programmer** [comment]
Reopen if issue persists. Thanks!
