### ISSUE TITLE
questions about cuda memory

### ISSUE THREAD

**Issue by NT-gwl** [sejong-rcv/INSANet#6]
Hello author, when I saved the weight of the training and start val, there was a problem of insufficient memory, and I did not modify any code.
![cuda_oom](https://github.com/user-attachments/assets/d2f5ec8c-60b7-462c-b32e-fe50698116b7)
my gpu is L40(must be A100?), about the "iou" calculation can be optimized?

**Comment by NT-gwl** [comment]
![Uploading QQ图片20241001154659.png…]()

**Comment by NT-gwl** [comment]
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/c5d50d8a-4280-4ea9-8f5a-e84181c77236">
</picture>

**Comment by NT-gwl** [comment]
https://github.com/user-attachments/assets/c5d50d8a-4280-4ea9-8f5a-e84181c77236

**Comment by NT-gwl** [comment]
(https://github.com/user-attachments/assets/13de2da1-f4b4-41ae-b836-5c394ad9c480)

**Comment by childult-programmer** [comment]
Did you get the same error if you lower the batch size (e.g. 1or2)?
We experimented with 2*A100. If OOM issue persists, you can find other efficient ways to calculate iou.
