### ISSUE TITLE
不好意思，没有看得懂您的数据集的组织形式，请问能否讲解一下

### ISSUE THREAD

**Issue by leileilei2000** [sejong-rcv/INSANet#7]

**Comment by childult-programmer** [comment]
Are you talking about the KAIST paired annotation? or datasets.py?
Please refer to [AR-CNN](https://github.com/luzhang16/AR-CNN) for annotation.

If your question is about datasets.py, please be a little more specific.

**Comment by leileilei2000** [comment]
> 您说的是 KAIST 配对注释吗？还是 datasets.py？注释请参考 [AR-CNN](https://github.com/luzhang16/AR-CNN)。
> 
> 如果您的问题与 datasets.py 有关，请更具体一些。

不好意思是我没表达清楚，我想问的是，如果我要用LLVIP数据集训练，那么我在设置LLVIP文件夹时，它的images和labels应该如何分配，我仅仅想知道不同模态的图像和标签应该在文件夹中如何安排

**Comment by childult-programmer** [comment]
Sorry for late response. Please refer the image (for LLVIP)!
![IMG_0300](https://github.com/user-attachments/assets/d3e02b10-3469-45db-bec5-5f7c087245f1)

**Comment by zzM-413** [comment]
Hello,I would like to ask how to train and evaluate on the LLVIP dataset

**Comment by childult-programmer** [comment]
@zzM-413 
Training and evaluation on the LLVIP dataset same as KAIST dataset.
One difference is that OBJ_LOAD_CONDITION in config(see [config.py](https://github.com/sejong-rcv/INSANet/blob/167237ec2291eaadb16707ff226b4058b43eb818/src/config.py#L61)) follows the range of image width and height in KAIST dataset, so you can either adjust it to LLVIP, or not to use. This is also true for evaluation code.

**Comment by zzM-413** [comment]
Thank you for your detailed response.




曾经的小纯洁丶oc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sejong-rcv/INSANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sejong-rcv/INSANet] 不好意思，没有看得懂您的数据集的组织形式，请问能否讲解一下 (Issue #7)





 
@zzM-413
 Training and evaluation on the LLVIP dataset same as KAIST dataset.
 One difference is that OBJ_LOAD_CONDITION in config(see config.py) follows the range of image width and height in KAIST dataset, so you can either adjust it to LLVIP, or not to use. This is also true for evaluation code.
